import type { ToolDef } from "../types";

// Full iLovePDF-parity catalog. `implemented: true` tools work end-to-end today;
// others render in the UI (nothing left behind) and are clearly marked "coming soon".
export const TOOLS: ToolDef[] = [
  // ---------------- Organize ----------------
  {
    slug: "merge-pdf",
    operation: "merge",
    name: "Merge PDF",
    category: "organize",
    description: "Combine multiple PDFs in the order you want into one file.",
    accept: "application/pdf",
    multiple: true,
    implemented: true,
    options: [],
  },
  {
    slug: "split-pdf",
    operation: "split",
    name: "Split PDF",
    category: "organize",
    description: "Separate pages into independent PDF files by ranges.",
    accept: "application/pdf",
    multiple: false,
    implemented: true,
    options: [
      {
        kind: "select",
        name: "mode",
        label: "Split mode",
        default: "ranges",
        options: [
          { value: "ranges", label: "Custom ranges" },
          { value: "everyN", label: "Every N pages" },
          { value: "individual", label: "One PDF per page" },
        ],
      },
      {
        kind: "text",
        name: "ranges",
        label: "Ranges (e.g. 1-3, 4-6, 7)",
        placeholder: "1-3, 4-6",
        default: "",
      },
      {
        kind: "number",
        name: "everyN",
        label: "Pages per file (Every N mode)",
        min: 1,
        default: 1,
      },
    ],
  },
  {
    slug: "remove-pages",
    operation: "remove-pages",
    name: "Remove Pages",
    category: "organize",
    description: "Delete unwanted pages from a PDF.",
    accept: "application/pdf",
    multiple: false,
    implemented: true,
    options: [
      {
        kind: "text",
        name: "pages",
        label: "Pages to remove (e.g. 2, 5-7)",
        placeholder: "2, 5-7",
        default: "",
      },
    ],
  },
  {
    slug: "extract-pages",
    operation: "extract-pages",
    name: "Extract Pages",
    category: "organize",
    description: "Pull selected pages into a new PDF.",
    accept: "application/pdf",
    multiple: false,
    implemented: true,
    options: [
      {
        kind: "text",
        name: "pages",
        label: "Pages to extract (e.g. 1, 3-5)",
        placeholder: "1, 3-5",
        default: "",
      },
    ],
  },
  {
    slug: "organize-pdf",
    operation: "organize",
    name: "Organize PDF",
    category: "organize",
    description: "Reorder pages by providing the new page order.",
    accept: "application/pdf",
    multiple: false,
    implemented: true,
    options: [
      {
        kind: "text",
        name: "order",
        label: "New page order (e.g. 3,1,2,4)",
        placeholder: "3,1,2,4",
        default: "",
      },
    ],
  },
  {
    slug: "rotate-pdf",
    operation: "rotate",
    name: "Rotate PDF",
    category: "organize",
    description: "Rotate all or selected pages.",
    accept: "application/pdf",
    multiple: false,
    implemented: true,
    options: [
      {
        kind: "select",
        name: "angle",
        label: "Rotation",
        default: "90",
        options: [
          { value: "90", label: "90° clockwise" },
          { value: "180", label: "180°" },
          { value: "270", label: "90° counter-clockwise" },
        ],
      },
      {
        kind: "text",
        name: "pages",
        label: "Pages (blank = all, e.g. 1,3-4)",
        placeholder: "all",
        default: "",
      },
    ],
  },
  {
    slug: "smart-split-pdf",
    operation: "smart-split",
    name: "Smart Split PDF",
    category: "organize",
    description: "AI-assisted splitting that detects logical document boundaries.",
    accept: "application/pdf",
    multiple: false,
    implemented: false,
    isNew: true,
    options: [],
  },
  {
    slug: "scan-to-pdf",
    operation: "jpg-to-pdf",
    name: "Scan to PDF",
    category: "organize",
    description: "Capture scans from your device camera into a PDF.",
    accept: "image/*",
    multiple: true,
    implemented: false,
    options: [],
  },

  // ---------------- Optimize ----------------
  {
    slug: "compress-pdf",
    operation: "compress",
    name: "Compress PDF",
    category: "optimize",
    description: "Reduce PDF file size while optimizing structure.",
    accept: "application/pdf",
    multiple: false,
    implemented: true,
    options: [
      {
        kind: "select",
        name: "level",
        label: "Compression level",
        default: "recommended",
        options: [
          { value: "extreme", label: "Extreme" },
          { value: "recommended", label: "Recommended" },
          { value: "less", label: "Less (high quality)" },
        ],
      },
    ],
  },
  {
    slug: "repair-pdf",
    operation: "repair",
    name: "Repair PDF",
    category: "optimize",
    description: "Recover data from a damaged or corrupt PDF.",
    accept: "application/pdf",
    multiple: false,
    implemented: false,
    options: [],
  },
  {
    slug: "ocr-pdf",
    operation: "ocr",
    name: "OCR PDF",
    category: "optimize",
    description: "Convert scanned PDFs into searchable, selectable text.",
    accept: "application/pdf",
    multiple: false,
    implemented: false,
    options: [],
  },

  // ---------------- Convert ----------------
  {
    slug: "jpg-to-pdf",
    operation: "jpg-to-pdf",
    name: "JPG to PDF",
    category: "convert",
    description: "Convert JPG/PNG images into a single PDF.",
    accept: "image/jpeg,image/png",
    multiple: true,
    implemented: true,
    options: [
      {
        kind: "select",
        name: "orientation",
        label: "Orientation",
        default: "portrait",
        options: [
          { value: "portrait", label: "Portrait" },
          { value: "landscape", label: "Landscape" },
        ],
      },
      {
        kind: "number",
        name: "margin",
        label: "Margin (pt)",
        min: 0,
        max: 100,
        default: 0,
      },
    ],
  },
  {
    slug: "pdf-to-jpg",
    operation: "pdf-to-jpg",
    name: "PDF to JPG",
    category: "convert",
    description: "Convert each PDF page into a JPG image.",
    accept: "application/pdf",
    multiple: false,
    implemented: false,
    options: [],
  },
  {
    slug: "word-to-pdf",
    operation: "word-to-pdf",
    name: "Word to PDF",
    category: "convert",
    description: "Convert DOC/DOCX files to PDF.",
    accept: ".doc,.docx",
    multiple: false,
    implemented: false,
    options: [],
  },
  {
    slug: "excel-to-pdf",
    operation: "excel-to-pdf",
    name: "Excel to PDF",
    category: "convert",
    description: "Convert XLS/XLSX spreadsheets to PDF.",
    accept: ".xls,.xlsx",
    multiple: false,
    implemented: false,
    options: [],
  },
  {
    slug: "powerpoint-to-pdf",
    operation: "powerpoint-to-pdf",
    name: "PowerPoint to PDF",
    category: "convert",
    description: "Convert PPT/PPTX slideshows to PDF.",
    accept: ".ppt,.pptx",
    multiple: false,
    implemented: false,
    options: [],
  },
  {
    slug: "pdf-to-word",
    operation: "pdf-to-word",
    name: "PDF to Word",
    category: "convert",
    description: "Convert PDF into editable DOC/DOCX.",
    accept: "application/pdf",
    multiple: false,
    implemented: false,
    options: [],
  },
  {
    slug: "pdf-to-excel",
    operation: "pdf-to-excel",
    name: "PDF to Excel",
    category: "convert",
    description: "Pull data from PDF into Excel spreadsheets.",
    accept: "application/pdf",
    multiple: false,
    implemented: false,
    options: [],
  },
  {
    slug: "pdf-to-powerpoint",
    operation: "pdf-to-powerpoint",
    name: "PDF to PowerPoint",
    category: "convert",
    description: "Convert PDF into editable PPT/PPTX.",
    accept: "application/pdf",
    multiple: false,
    implemented: false,
    options: [],
  },
  {
    slug: "html-to-pdf",
    operation: "html-to-pdf",
    name: "HTML to PDF",
    category: "convert",
    description: "Convert a webpage URL to PDF.",
    accept: "text/html",
    multiple: false,
    implemented: false,
    options: [],
  },
  {
    slug: "pdf-to-pdfa",
    operation: "pdf-to-pdfa",
    name: "PDF to PDF/A",
    category: "convert",
    description: "Convert to ISO-standardized PDF/A for archiving.",
    accept: "application/pdf",
    multiple: false,
    implemented: false,
    options: [],
  },
  {
    slug: "pdf-to-markdown",
    operation: "pdf-to-markdown",
    name: "PDF to Markdown",
    category: "convert",
    description: "Turn PDFs into Markdown; preserve headings, tables, lists, links.",
    accept: "application/pdf",
    multiple: false,
    implemented: false,
    isNew: true,
    options: [],
  },

  // ---------------- Edit ----------------
  {
    slug: "edit-pdf",
    operation: "edit",
    name: "Edit PDF",
    category: "edit",
    description: "Add text, images, shapes and annotations.",
    accept: "application/pdf",
    multiple: false,
    implemented: false,
    options: [],
  },
  {
    slug: "watermark-pdf",
    operation: "watermark",
    name: "Watermark",
    category: "edit",
    description: "Stamp text over your PDF with position and transparency.",
    accept: "application/pdf",
    multiple: false,
    implemented: true,
    options: [
      {
        kind: "text",
        name: "text",
        label: "Watermark text",
        placeholder: "CONFIDENTIAL",
        default: "CONFIDENTIAL",
      },
      {
        kind: "number",
        name: "opacity",
        label: "Opacity (%)",
        min: 5,
        max: 100,
        default: 30,
      },
      {
        kind: "number",
        name: "fontSize",
        label: "Font size",
        min: 8,
        max: 144,
        default: 48,
      },
      {
        kind: "number",
        name: "angle",
        label: "Rotation angle",
        min: 0,
        max: 360,
        default: 45,
      },
    ],
  },
  {
    slug: "page-numbers",
    operation: "page-numbers",
    name: "Page Numbers",
    category: "edit",
    description: "Add page numbers with position and typography control.",
    accept: "application/pdf",
    multiple: false,
    implemented: true,
    options: [
      {
        kind: "select",
        name: "position",
        label: "Position",
        default: "bottom-center",
        options: [
          { value: "bottom-center", label: "Bottom center" },
          { value: "bottom-right", label: "Bottom right" },
          { value: "bottom-left", label: "Bottom left" },
          { value: "top-center", label: "Top center" },
          { value: "top-right", label: "Top right" },
          { value: "top-left", label: "Top left" },
        ],
      },
      {
        kind: "number",
        name: "startAt",
        label: "Start number",
        min: 0,
        default: 1,
      },
      {
        kind: "number",
        name: "fontSize",
        label: "Font size",
        min: 6,
        max: 48,
        default: 12,
      },
    ],
  },
  {
    slug: "crop-pdf",
    operation: "crop",
    name: "Crop PDF",
    category: "edit",
    description: "Crop margins or select areas of your pages.",
    accept: "application/pdf",
    multiple: false,
    implemented: false,
    options: [],
  },
  {
    slug: "pdf-forms",
    operation: "forms",
    name: "PDF Forms",
    category: "edit",
    description: "Detect, create and fill interactive PDF form fields.",
    accept: "application/pdf",
    multiple: false,
    implemented: false,
    isNew: true,
    options: [],
  },

  // ---------------- Security ----------------
  {
    slug: "protect-pdf",
    operation: "protect",
    name: "Protect PDF",
    category: "security",
    description: "Encrypt and password-protect a PDF.",
    accept: "application/pdf",
    multiple: false,
    implemented: false,
    options: [],
  },
  {
    slug: "unlock-pdf",
    operation: "unlock",
    name: "Unlock PDF",
    category: "security",
    description: "Remove password security from a PDF you can access.",
    accept: "application/pdf",
    multiple: false,
    implemented: false,
    options: [],
  },
  {
    slug: "redact-pdf",
    operation: "redact",
    name: "Redact PDF",
    category: "security",
    description: "Permanently remove sensitive information.",
    accept: "application/pdf",
    multiple: false,
    implemented: false,
    options: [],
  },
  {
    slug: "compare-pdf",
    operation: "compare",
    name: "Compare PDF",
    category: "security",
    description: "Spot changes between two document versions.",
    accept: "application/pdf",
    multiple: true,
    implemented: false,
    options: [],
  },

  // ---------------- Sign ----------------
  {
    slug: "sign-pdf",
    operation: "sign",
    name: "Sign PDF",
    category: "sign",
    description: "Self-sign or request electronic signatures.",
    accept: "application/pdf",
    multiple: false,
    implemented: false,
    options: [],
  },

  // ---------------- AI ----------------
  {
    slug: "summarize-pdf",
    operation: "summarize",
    name: "AI Summarizer",
    category: "ai",
    description: "Generate concise summaries with key points.",
    accept: "application/pdf",
    multiple: false,
    implemented: false,
    isNew: true,
    options: [],
  },
  {
    slug: "translate-pdf",
    operation: "translate",
    name: "Translate PDF",
    category: "ai",
    description: "AI translation preserving layout and formatting.",
    accept: "application/pdf",
    multiple: false,
    implemented: false,
    isNew: true,
    options: [],
  },
  {
    slug: "extract-data",
    operation: "extract-data",
    name: "Data Extraction",
    category: "ai",
    description: "Extract structured data to JSON/CSV/Excel.",
    accept: "application/pdf",
    multiple: false,
    implemented: false,
    isNew: true,
    options: [],
  },
];

export const CATEGORY_LABELS: Record<ToolDef["category"], string> = {
  organize: "Organize PDF",
  optimize: "Optimize PDF",
  convert: "Convert PDF",
  edit: "Edit PDF",
  security: "PDF Security",
  sign: "Sign PDF",
  ai: "PDF Intelligence",
};

export const CATEGORY_ORDER: ToolDef["category"][] = [
  "organize",
  "optimize",
  "convert",
  "edit",
  "security",
  "sign",
  "ai",
];

export function getToolBySlug(slug: string): ToolDef | undefined {
  return TOOLS.find((t) => t.slug === slug);
}
